version: '2.3'

services:
  lnd:
    build: ./data-sources/lnd
    volumes:
      - shared:/home/lnd/.lnd/
      - ./data-sources/lnd/lnd.conf:/home/lnd/.lnd/lnd.conf
      - ./data-sources/bitcoind/bitcoin.conf:/home/lnd/.bitcoin/bitcoin.conf
    entrypoint: ["./start-lnd.sh"]
    ports:
      - "9735:9735"
      - "10009:10009"
  bitcoind:
    build: ./data-sources/bitcoind
    volumes:
      - ./data-sources/bitcoind/bitcoin.conf:/home/bitcoin/.bitcoin/bitcoin.conf
      # - type: bind
        # source: /mnt/volume_nyc1_01/.bitcoin/
        # target: /home/bitcoin/.bitcoin/
    command: bitcoind  --printtoconsole -rpcallowip=0.0.0.0/0
    ports:
      - "18443:18443"
      - "8332:8332"
      - "8333:8333"
  app:
    image: node:8
    working_dir: /home/node/app
    depends_on:
      - redis
      - lnd
      - bitcoind
    volumes:
      - shared:/home/node/.lnd/
      - ./data-sources/lnd/lnd.conf:/home/node/.lnd/lnd.conf
      - ./:/home/node/app
    ports:
      - "9001:9000"
      - "3304:3304"
      - "3009:3009"
      - "3098:3098"
      - "3432:3432"
    command: "npm start --unsafe-perm"
    environment:
      - RPC_PORT=18443
      - RPC_HOST=bitcoind
      - RPC_USERNAME=rpcuser
      - RPC_PASSWORD=rpcpassword
      - GRPC_SSL_CIPHER_SUITES=HIGH+ECDSA
      - LNSERVICE_LND_DIR=/home/node/.lnd
      - LNSERVICE_CHAIN=bitcoin
      - LNSERVICE_NETWORK=regtest
      - LNSERVICE_SECRET_KEY=rpcpassword
      - LND_HOST=lnd
      - LND_GRPC_PORT=10009
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DB_NAME=proofofchat
      - REDIS_URL=redis://redis:6379

  mongodb:
    build: ./data-sources/mongodb
    volumes:
      - ./data-sources/mongodb/mongod.conf:/etc/mongod.conf
    command: mongod -f /etc/mongod.conf
    ports:
      - "27017:27017"
      - "28017:28017"

  redis:
    image: redis

volumes:
  shared:
    driver: local
